name: dagger

on:
  pull_request:
    branches: [main]

jobs:
  publish:
    name: Publish Image To ECR
    environment: aws-announcer
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ vars.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Login to Amazon ECR
        id: login-ecr-public
        uses: aws-actions/amazon-ecr-login@v2
        with:
          registry-type: public

      - name: Call Dagger Function to Test code
        uses: dagger/dagger-for-github@v5
        with:
          verb: call
          module: dagger
          args: publish --source=src --repo-name=aws-announcer --repo-alias=i7g9w0t5 --image-tags=v0.0.1
